/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Group {
  bg_color: string;
  id: Generated<number>;
  name: string;
  text_color: string;
}

export interface GroupPermission {
  group_id: number;
  permission: string;
}

export interface UserGroup {
  group_id: number;
  user_id: number;
}

export interface Users {
  email: string;
  id: Generated<number>;
  password: string;
  username: string;
}

export interface DB {
  group: Group;
  group_permission: GroupPermission;
  user_group: UserGroup;
  users: Users;
}
